### ISSUE TITLE
minified Warning in "non-production" environment using Webpack 4

### ISSUE THREAD

**Issue by HerrVoennchen** [reactjs/redux#2881] opened 2018-03-09 11:04 UTC
**Do you want to request a *feature* or report a *bug*?**  

Probably Bug

**What is the current behavior?**

I'm migrating my Webpack 3 config to 4 and got it working. But on the development build running in webpack-dev-server I got the warning:

> warning.js:10 You are currently using minified code outside of NODE_ENV === 'production'. This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or DefinePlugin for webpack (http://stackoverflow.com/questions/30030031) to ensure you have the correct code for your production build.

NODE_ENV is defnitly unset (undefined) since I only set it on production so no idea why this pops up.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar.**

I have a repo here to develop my config. there is a Webpack 4 branch (and the current Webpack 3 version on Master). Note that currently I only tested the "development" mode with webpack-dev-server. I didn't tested the "production" output yet.

https://github.com/HerrVoennchen/sample-project/tree/Webpack4-sort-of-working

**What is the expected behavior?**

No Warning in "development" or non-production mode.

**Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?**

No Warning on Webpack 3

using redux 3.7.2

Warning appears on Chrome 65 as well as FF 58/59

**Comment by timdorr** [comment] 2018-03-09 14:32
Duplicate of #2878. This is a webpack issue, so please reach out to their appropriate support forums.

**Closed by timdorr** 2018-03-09 14:32 UTC

**Comment by HerrVoennchen** [comment] 2018-03-09 14:43
Read the thread, you're right. thx for pointing out.
