### ISSUE TITLE
Why "combinReduers" can not work at my project today suddenly, which could work well yesterday?

### ISSUE THREAD

**Issue by caojinli** [reactjs/redux#1681] opened 2016-04-29 07:34 UTC
import { combineReducers } from 'redux'
import { routerReducer as router } from 'react-router-redux'
import counter from './modules/counter'
import docManage from './doc'

export default combineReducers({ // error happened
  counter,
  docManage,
  router
})
Uncaught TypeError: (0 , _redux.combineReducers) is not a functionObject.defineProperty.value @ rootReducer.js:6__webpack_require__ @ bootstrap 8921782a133419f3cb76:585fn @ bootstrap 8921782a133419f3cb76:109exports.__esModule @ index.js:6__webpack_require__ @ bootstrap 8921782a133419f3cb76:585fn @ bootstrap 8921782a133419f3cb76:109(anonymous function) @ wrapActionCreators.js:6__webpack_require__ @ bootstrap 8921782a133419f3cb76:585fn @ bootstrap 8921782a133419f3cb76:109exports.__esModule @ connect.js:18__webpack_require__ @ bootstrap 8921782a133419f3cb76:585fn @ bootstrap 8921782a133419f3cb76:109exports.__esModule @ index.js:10__webpack_require__ @ bootstrap 8921782a133419f3cb76:585fn @ bootstrap 8921782a133419f3cb76:109(anonymous function) @ bootstrap 8921782a133419f3cb76:631__webpack_require__ @ bootstrap 8921782a133419f3cb76:585(anonymous function) @ bootstrap 8921782a133419f3cb76:631(anonymous function) @ bootstrap 8921782a133419f3cb76:631

**Comment by gaearon** [comment] 2016-04-29 11:19
Hi! Unfortunately this is not enough information to help you. Please provide a project reproducing the issue.

**Comment by gaearon** [comment] 2016-05-02 16:46
I’m closing as there is not enough information here, and it’s most likely a usage issue. Please refer to examples to see the correct usage.

**Closed by gaearon** 2016-05-02 16:46 UTC

**Comment by caojinli** [comment] 2016-05-03 01:16
What I can give more information is I added some module by "npm" like thunk. then it got error.

**Comment by gaearon** [comment] 2016-05-03 01:53
Please provide a project reproducing the issue. I can’t find a way to reproduce this, so unfortunately there is no way I could help you.

**Comment by caojinli** [comment] 2016-05-03 02:04
I can not attach my zipped  project about 606KB size, for error from git "Something went really wrong, and we can’t process that file. ". Is there other way I could attach my project?

**Comment by caojinli** [comment] 2016-05-03 02:09
"Something went really wrong, and we can’t process that file. " when I try to attach my project code, Is there other way to attach my code?

**Comment by gaearon** [comment] 2016-05-03 02:13
Please delete `node_modules` from it if it’s there.

**Comment by gaearon** [comment] 2016-05-03 02:14
You can create a repository on GitHub and push it there rather than attach it.

**Comment by caojinli** [comment] 2016-05-03 02:42
After I enter" npm publish", console response me "+ prodoc@0.0.2", I think my project has been updated into github now, but I can not search it at github, don't know why.

**Comment by caojinli** [comment] 2016-05-03 03:26
npm ERR! extraneous: inline-style-prefixer@1.0.2 D:\react\react-redux-starter-kit\node_modules\inline-style-prefixer
npm ERR! extraneous: isomorphic-fetch@2.2.1 D:\react\react-redux-starter-kit\node_modules\isomorphic-fetch
npm ERR! extraneous: keycode@2.1.1 D:\react\react-redux-starter-kit\node_modules\keycode
npm ERR! extraneous: lodash.merge@4.3.2 D:\react\react-redux-starter-kit\node_modules\lodash.merge
npm ERR! extraneous: lodash.throttle@4.0.1 D:\react\react-redux-starter-kit\node_modules\lodash.throttle
npm ERR! extraneous: react-event-listener@0.1.1 D:\react\react-redux-starter-kit\node_modules\react-event-listener
npm ERR! extraneous: recompose@0.15.1 D:\react\react-redux-starter-kit\node_modules\recompose
npm ERR! extraneous: redux-logger@2.6.1 D:\react\react-redux-starter-kit\node_modules\redux-logger
npm ERR! extraneous: simple-assign@0.1.0 D:\react\react-redux-starter-kit\node_modules\simple-assign
npm ERR! extraneous: whatwg-fetch@0.9.0 D:\react\react-redux-starter-kit\node_modules\whatwg-fetch

**Comment by markerikson** [comment] 2016-05-03 03:32
@caojinli : so far, it looks like you've tried to publish your repository as an NPM package, not create a repo on Github and make it available.  Also, those "extraneous" warnings have nothing to do with Redux - that's NPM saying that there's a mismatch between what packages are in `node_modules`, and what's listed in your package.json.

**Comment by caojinli** [comment] 2016-05-03 03:48
The project had been located at URL of https://github.com/caojinli/prodoc, who can get my project with error "combinReduer"? Thanks a lot.

**Comment by caojinli** [comment] 2016-05-03 03:50
@markerikson I did publish my project into github yet and wish you could supply kindly help, thank you.

**Comment by gaearon** [comment] 2016-05-03 12:08
@caojinli 

When I run `npm install` inside it, I get

```
npm WARN EJSONPARSE Failed to parse json
npm WARN EJSONPARSE Unexpected end of input at 171:2
npm WARN EJSONPARSE 
npm WARN EJSONPARSE ^
```

This means `package.json` is broken. If we look into `package.json`, the `scripts` section ends abruptly:

```js
    "deploy": "better-npm-run deploy",
    "flow:check": "babel-node bin/flow-check",
    "codecov": "cat coverage/*/lcov.info | codecov"
  ,
  "betterScripts": {
```

I found the exact place of error with http://jsonlint.com/ that formats JSON.
After adding the missing `}` before the comma, I was able to run `npm install`.

After I ran `npm start`, I got this:

```
ERROR in ./src/redux/actions/manageDoc.js
Module not found: Error: Cannot resolve module 'isomorphic-fetch' in /Users/dan/p/prodoc/src/redux/actions
 @ ./src/redux/actions/manageDoc.js 23:23-50
```

I ran

```
npm install --save isomorphic-fetch
```

to fix it.

Finally, after running `npm start` again, I got the error you described:

```
rootReducer.js:6 Uncaught TypeError: (0 , _redux.combineReducers) is not a function
Head.js:66 Uncaught TypeError: (0 , _reactRedux.connect) is not a function
```

It turned out that you have [`resolve.root` Webpack option enabled](https://github.com/caojinli/prodoc/blob/35d3a629bc105d71e804360204c75e80d6aeaf88/build/webpack.config.js#L18) that [lets you import modules by their paths relative to the root folder](https://github.com/caojinli/prodoc/blob/35d3a629bc105d71e804360204c75e80d6aeaf88/src/routes/index.js#L4-L8). The problem is **you have a [folder called `redux`](https://github.com/caojinli/prodoc/blob/35d3a629bc105d71e804360204c75e80d6aeaf88/src/redux/index.js) in your project** so now all imports of `redux` resolve to that folder rather than to the real Redux.

Removing `resolve.root` from Webpack config fixes the issue. 

In the future we would prefer that you ask questions like this on StackOverflow, not an the Redux issue tracker. Redux is a very specific library, but your problems seem related to using a mix of 20 technologies that you together without deeply understanding how each of them works.

**Copy-pasting configs from boilerplate projects always leads to hard-to-debug issues like this.** It’s easy to miss somebody’s configuration decisions when you’re not the one making them. Don’t use boilerplate projects unless you understand each and every technology it uses!

You don’t need a boilerplate to start learning Redux. If you just want to start learning Redux, copy [this HTML page](https://raw.githubusercontent.com/reactjs/redux/master/examples/counter-vanilla/index.html) and start learning! You can always look at all those other projects later when you’re more comfortable with Redux and other libraries.

**Comment by caojinli** [comment] 2016-05-05 05:39
@gaearon First of all, thank you very much, I did learn much from your reply.
 If I disable resolve.root  from webpack config file, I got some new  errors which could work well previously.
ERROR in ./src/redux/configureStore.js
Module not found: Error: Cannot resolve module 'containers/DevTools' in D:\react\react-redux-starter-kit\src\redux
 @ ./src/redux/configureStore.js 29:75-105

ERROR in ./src/containers/Root.js
Module not found: Error: Cannot resolve module 'containers/DevTools' in D:\react\react-redux-starter-kit\src\containers
 @ ./src/containers/Root.js 120:25-55

ERROR in ./src/routes/index.js
Module not found: Error: Cannot resolve module 'layouts/CoreLayout/CoreLayout' in D:\react\react-redux-starter-kit\src\routes
 @ ./src/routes/index.js 13:18-58

ERROR in ./src/routes/index.js
Module not found: Error: Cannot resolve module 'views/HomeView/HomeView' in D:\react\react-redux-starter-kit\src\routes
 @ ./src/routes/index.js 17:16-50

ERROR in ./src/routes/index.js
Module not found: Error: Cannot resolve module 'views/HomeView/teachers' in D:\react\react-redux-starter-kit\src\routes
 @ ./src/routes/index.js 21:16-50

ERROR in ./src/routes/index.js
Module not found: Error: Cannot resolve module 'views/HomeView/docView' in D:\react\react-redux-starter-kit\src\routes
 @ ./src/routes/index.js 25:15-48

Plus, I did rename the redux folder from my project after I read your reponse to viod what you mentioned that program will use wrong "redux" instead of real "redux". but unfortunately I still can not run it even I renamed the folder of redux.

**Comment by caojinli** [comment] 2016-05-05 05:46
@gaearon I foud that the resolve.root in webpack.config.js actually refer to the [redux of src](https://github.com/caojinli/prodoc/tree/master/src/redux), so I can not disable it.

**Comment by gaearon** [comment] 2016-05-06 00:24
>If I disable resolve.root from webpack config file, I got some new errors which could work well previously.

Yes, because you can no longer use absolute paths that are automatically resolved. This is the whole point—you should either rename your folder to be called something other than `redux` so that `resolve.root` doesn’t mess it up, or change all your imports to be relative (e.g. `../views/HomeView/docView` rather than `views/HomeView/docView`). You can’t have both a folder named `redux` and the `resolve.root` option and expect this to work.

**Comment by caojinli** [comment] 2016-05-06 05:24
@gaearon I copied my business codes(including views, reduxs-reducers, components, containers and etc) to another project which could work every well, using same configration(download from github), the working very well project got same error. If I removed my business codes from it and the project worked very well again. So I dare to say it caused by my business code. nothing related to webpack config and there was a folder of redux in my src.

**Comment by gaearon** [comment] 2016-05-06 11:00
If you see this exact error:

```js
rootReducer.js:6 Uncaught TypeError: (0 , _redux.combineReducers) is not a function
Head.js:66 Uncaught TypeError: (0 , _reactRedux.connect) is not a function
```

There is no way it can be caused by your business code. This is the error caused by `resolve.root` configuration. `redux` provides those exports so the only way you can get this error is if you resolve `redux` to something other than its npm package.

Of course, any other errors may have different origins.
