### ISSUE TITLE
Alternative to callbacks recipe/example

### ISSUE THREAD

**Issue by brigand** [reactjs/redux#1980] opened 2016-09-22 23:45 UTC
There are times where you basically want a callback, but that's strongly discouraged. I'd like to have a recipe for this because it comes up a lot for me. I'm going to share my solution which I'm not too happy about, and hopefully get feedback on it, and then I'll create a PR to add the recipe or an example.

The most common situation for this is: you have a form modal. The user enters some stuff and then you send it to the server. You wait until there's a response, and then you close the modal if it succeeds. This is super easy with promises or callbacks, but it's tricky in redux.

My current solution is 'receipts'. The component creates a random id and stores it on `this`; it sends that as part of the action. The request is sent with middleware. The receipt id is attached to the success action. The receipt reducer 'signs' it, resulting in a state with `{[receiptId]: true, ...}`. The full receipt state is passed to a react component via connect. In the react component's componentWillReceiveProps checks if the receipt changed from `false` to `true`. If so, it does the thing like closing the modal.

Here's some example code: https://gist.github.com/brigand/9186cafa7ea40841121057a2547c523e

Should an exception to the 'no callbacks' rule be made to keep this simpler?

Of course, I'm open to very different ideas about how to solve this problem. Is this a problem you've run into yourself, or maybe you've found ways to avoid this?

**Comment by markerikson** [comment] 2016-09-22 23:58
I'm not sure what you mean by a "no callback rule", specifically.  However, you may be interested in this question I answered on SO the other day: http://stackoverflow.com/questions/39610970/how-to-pass-a-thunk-or-callback-function-into-a-redux-action-serializing-functi/39622799#39622799 .

**Comment by brigand** [comment] 2016-09-23 00:13
Yeah, the redux docs you linked to in that post say "It is highly recommended that you only put plain serializable objects, arrays, and primitives into your store." which I interpret as callbacks in actions/state being bad. Also callbacks are bidirectional which breaks the unidirectional flow of flux/redux. I'm still not sure if that's worth compromising on or not.

**Comment by markerikson** [comment] 2016-09-23 00:22
Well, per my comments: if you're okay with time travel debugging probably not working as intended, go ahead and put callbacks in your actions and your state.

On the flip side, based on the description of your situation, I'm not sure why you'd actually need to go that route.  If you follow a dialog management approach like [the one described by Dan](http://stackoverflow.com/questions/35623656/how-can-i-display-a-modal-dialog-in-redux-that-performs-asynchronous-actions), then there's no need to have the component look for updated props to close itself.  This logic fits very well into thunks or sagas.  For example:

```js
function doStuffOnModalClicked(someParam) {
    return (dispatch, getState) {
        myAjaxLib.post("/saveTheThing", {someParam})
            .then(response => {
                dispatch({type : "THING_UPDATED", response);
                dispatch({type : "CLOSE_MODAL");
            });
    }
}
```

**Comment by brigand** [comment] 2016-09-23 00:46
Ah, I can see why this hasn't come up before. My situation is a combination of edge cases (multiple modal layers, passing data back to the parent on finish) and the goal of not making assumptions, which allows me to handle the edge cases without extra effort.

Hard avoidance of assumptions has served me well so far, but it's not popular enough to make it into official docs, as far as I can tell.

**Comment by markerikson** [comment] 2016-09-23 00:54
For what it's worth my own app can have stacked modals as well, and they're still centrally managed by a single DialogManager component.  It's basically the same technique that Dan describes, just with an array listing open modals instead of a single variable.  

Ultimately, though, per your original question: putting non-serializable stuff like functions into actions and your Redux store is generally discouraged because it breaks stuff like time-travel debugging, and other potential use cases like store persistence.  If you're okay with that, go ahead and do it.  But, it also sounds like it should be very feasible to architect your app so that's not necessary.

If you'd like to chat about this further, feel free to drop by the Reactiflux chat channels on Discord.  The invite link is at http://www.reactiflux.com .  Probably easier to discuss stuff there.

**Closed by markerikson** 2016-09-23 00:54 UTC

**Comment by brigand** [comment] 2016-09-23 01:04
Thanks for the feedback and links! I'll try to adapt my app to use these ideas.
