### ISSUE TITLE
Provider complaining about hot reloading store

### ISSUE THREAD

**Issue by julienvincent** [reactjs/redux#1459] opened 2016-02-28 23:29 UTC
Whenever I change store related code, I get the following message:

```
<Provider> does not support changing `store` on the fly. It is most likely that you see this error because you updated to Redux 2.x and React Redux 2.x which no longer hot reload reducers automatically. See https://github.com/rackt/react-redux/releases/tag/v2.0.0 for the migration instructions.
```

My store setup looks like this:

```javascript
import reducers from './reducers/index'

const devStore = () => {
    const store = createStore(
        reducers,
        initialState,
        compose(
            middleware
        )
    )

    if (module.hot) {
        module.hot.accept('./reducers', () => {
            const nextRootReducer = require('./reducers/index')
            store.replaceReducer(nextRootReducer)
        })
    }

    return store
}

const store = env.ENVIRONMENT == 'production' ? prodStore() : devStore()

export { store as default }
```

My module.hot check is in place. I am not sure how to go about debugging this. Any help is appreciated.

**Comment by gaearon** [comment] 2016-02-28 23:58
Since you import `<Provider>` from `react-redux`, https://github.com/reactjs/react-redux would be a more appropriate place for this issue.

What do you call “store-related code”? Updates to `store.js` are not supposed to be handled, so the warning sounds correct to me. Updates to reducers should be handled by that `module.hot` code.

If you still have issues please attach a project reproducing the issue. I’m closing because this is a Webpack usage question and not the library issue, and it is not about this repository.

**Closed by gaearon** 2016-02-28 23:58 UTC

**Comment by julienvincent** [comment] 2016-02-29 00:08
By store related code I mean actions or sagas. If it's expected to not hot reload actions or sagas then I will leave this as is, else I will open an issue under react-redux

**Comment by gaearon** [comment] 2016-02-29 00:13
Sagas don’t currently hot reload. (I’m actually not sure why; it feels like pausing existing sagas and restarting them would be a “good enough” solution for most cases. I think it would be great if there was something like `sagaMiddleware.replaceSagas(...sagas)` method. See also https://github.com/yelouafi/redux-saga/issues/22.)

**Comment by gaearon** [comment] 2016-02-29 00:13
And action creators likely don’t hot reload for you because you import them from sagas.

**Comment by julienvincent** [comment] 2016-02-29 00:21
Ah so there lies the problem. Glancing over that issue I can see how time travel is a problem with sagas, although I don't exactly need time travel in my use case so something like `replaceSaga` would be very useful. 

Anyway thanks for helping out, was bugging me for some time now

**Comment by gaearon** [comment] 2016-02-29 00:25
No problem. I think you would be welcome sending a PR to Redux Saga to implement something like `replaceSaga` and starting a discussion around it. cc @yelouafi

**Comment by faceyspacey** [comment] 2016-04-21 03:46
any word on sagas hot loading?

**Comment by gaearon** [comment] 2016-04-21 11:57
Please discuss this in Redux Saga repo. We’re not personally developing it 😉
